version: "3"

services:
  db:
    image: mysql:latest
    container_name: "car-spare-parts-db"
    ports:
      - "3306:3306"
    cap_add:
      - "SYS_NICE"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
